# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded autoscroll 1.1 [list source [file join $dir autoscroll.tcl]]
package ifneeded kswaplist 0.1.2 [list source [file join $dir kswaplist.tcl]]
package ifneeded pgu 1.0 [list source [file join $dir pgu.tcl]]
package ifneeded math::kstatistics 0.1.1 [list source [file join $dir statistics.tcl]]
package ifneeded text2pdf 0.2 [list source [file join $dir text2pdf.tcl]]
package ifneeded Scrolledframe 0.9.1 [list source [file join $dir sframe.tcl]]
package ifneeded anigif 1.3 [list source [file join $dir anigif.tcl]]
package ifneeded ktooltip 1.4.5 [list source [file join $dir ktooltip-1.4.5.tm]]
package ifneeded map::kpv_slippy 0.4 [list source [file join $dir kpv_slippy.tcl]]
package ifneeded uri 1.2.1 [list source [file join $dir uri-1.2.1.tm]]

set fname [file join $dir xphoto[info sharedlibextension]]
if {[file exists $fname]} {
    package ifneeded xphoto 1.0 "list $fname]; package provide xphoto 1.0"
}
 
